### ISSUE TITLE
Registrar usuario

### ISSUE THREAD

**Issue by EzeSosa** [7-Seven-Up/megastore-backend#2]
**Como** cliente **quiero** poder registrarme y crear una cuenta en la plataforma **para** realizar compras y acceder a mi historial de pedidos.

# Criterios de aceptación:

- Debe existir un formulario de registro que incluya: nombre, dirección de correo electrónico, contraseña y confirmación de contraseña.
- El correo electrónico debe ser único y validado.
- Los clientes deben poder iniciar sesión con sus credenciales después de activar su cuenta.

**Comment by Fedesan14** [comment]
@delgadomatias @EzeSosa @martinjcrosetto @ValeLattanzi, estuve pensando en la solucion para esta historia teniendo en cuenta que es el registro de un usuario y a su vez la activacion mediante un correo electronico

La idea es que un principio se haga una peticion http POST para crear el usuario, cuando este se crea se genera un token que se asocia a ese usuario y se almacena en BD. A su vez tiene un se le envia al correo electronico el token de activacion.
![image](https://github.com/user-attachments/assets/30e9c4be-04fd-4771-9c97-47174f99c127)

En el correo se deberia enviar una URL con el siguiente formato host/users/activate/{token} el cual coincide con un endpoint que exponemos en nuestro backend, esto hara que se busque el usuario y se setee el valor booleano "activated" como true y se redirecciona al usuario a una pagina del frontend que sea el login o una pagina de bienvenida (tambien pense en enviarle el correo de bienvenida que hizo mati ya)
![image](https://github.com/user-attachments/assets/9ffca218-9daf-474e-a53c-4f840cf3e262)

Puede pasar tambien que a la hora de registrar el usuario NO se haya enviado el mail, por lo que deberiamos darle la posibilidad al usuario que se reenvie el codigo de activacion asociado a el, para eso pense lo siguiente

![image](https://github.com/user-attachments/assets/41347ac2-f9ba-4c7e-b3a9-5a3c1eb7b80e)



Espero opiniones y sugerencias. Si les parece bien avanzamos con esta solución

**Comment by EzeSosa** [comment]
Estoy de acuerdo con la solución. En cuanto al token, ¿Utilizamos un UUID o implementamos un JWT? (De cualquier modo vamos a necesitar la librería para los JWT en un futuro)

**Comment by martinjcrosetto** [comment]
Me gusta la idea y concuerdo en el uso de JWT, además podríamos ver si sería necesario implementar un componente de renovación de tokens para cuando expiren, los usuarios podrían seguir utilizando la aplicación sin necesidad de volver a iniciar sesión constantemente.

**Comment by Fedesan14** [comment]
JWT no, ya que no vamos a tener claims (para lo cual se usa JWT), asi que no lo veo necesario. Lo que si podemos hacer es tener un generador de strings alphanumericos de varios carácteres o los mismos UUID

**Comment by delgadomatias** [comment]
Banco la solución, diría que usemos UUID

**Comment by ValeLattanzi** [comment]
Desconozco la verdad sobre usar UUID sobre JWT, pero como decidan
